### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by mrjonny2** [dannycoates/hapi-fxa-oauth#4]
Is there a short use example to go along with this library?

**Comment by rfk** [comment]
We should make a standalone example, but as a start you can see it used in the fxa-auth-server here:

Registration: https://github.com/mozilla/fxa-auth-server/blob/master/lib/server.js#L151
Use: https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L631

**Comment by mrjonny2** [comment]
Sorry to sound a bit thick, but can I ask why in that you guys have used both Hawk and the fxa oath authentication?

**Comment by rfk** [comment]
> why in that you guys have used both Hawk and the fxa oath authentication

Simply as a convenience for clients; if the client has a hawk session token, they could easily mint an oauth token with the appropriate permissions, but this would be an extra round-trip for the client.
